import java.text.*;

import java.util.*;

import java.awt.*;

import java.io.BufferedReader;

import java.io.BufferedWriter;

import java.io.FileInputStream;

import java.io.FileNotFoundException;

import java.io.FileOutputStream;

import java.io.FileReader;

import java.io.FileWriter;

import java.io.IOException;
import java.io.PrintWriter;

import javax.swing.JFrame;

import javax.swing.JOptionPane;

public class rest extends javax.swing.JFrame {

Double firstnum;

Double secondnum;

Double Result;

String Operations;



    /**

     * Creates new form rest

     */

    public rest() {

        initComponents();

    }



    /**

     * This method is called from within the constructor to initialize the form.

     * WARNING: Do NOT modify this code. The content of this method is always

     * regenerated by the Form Editor.

     */

    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents

    private void initComponents() {



        jPanel9 = new javax.swing.JPanel();

        jPanel1 = new javax.swing.JPanel();

        jTxtMealCost = new javax.swing.JTextField();

        jtxtDrinkCost = new javax.swing.JTextField();

        jTxtDeliveryCost = new javax.swing.JTextField();

        jTextField10 = new javax.swing.JTextField();

        jTextField11 = new javax.swing.JTextField();

        jTextField12 = new javax.swing.JTextField();

        jPanel2 = new javax.swing.JPanel();

        jChecbxChikBuger = new javax.swing.JCheckBox();

        jChkbxBugerMeal = new javax.swing.JCheckBox();

        jCheckBxBacon = new javax.swing.JCheckBox();

        jTxtBugerNo = new javax.swing.JTextField();

        jTxtBugerMeal = new javax.swing.JTextField();

        jTxtBacon = new javax.swing.JTextField();

        jTextField5 = new javax.swing.JTextField();

        jCombDrink = new javax.swing.JComboBox<>();

        jCheckbxTax = new javax.swing.JCheckBox();

        jCheckBoxHomeDeliver = new javax.swing.JCheckBox();

        jSeparator1 = new javax.swing.JSeparator();

        jPanel3 = new javax.swing.JPanel();

        jTextField13 = new javax.swing.JTextField();

        jTextField14 = new javax.swing.JTextField();

        jTextField15 = new javax.swing.JTextField();

        jTextSubtotal = new javax.swing.JTextField();

        jTextToatal = new javax.swing.JTextField();

        jTextTax = new javax.swing.JTextField();

        jPanel4 = new javax.swing.JPanel();

        jTabbedPane1 = new javax.swing.JTabbedPane();

        jPanel7 = new javax.swing.JPanel();

        jScrollPane1 = new javax.swing.JScrollPane();

        jTextArea1 = new javax.swing.JTextArea();

        jPanel8 = new javax.swing.JPanel();

        jTxtDisplay = new javax.swing.JTextField();

        jBtn7 = new javax.swing.JButton();

        jbtn4 = new javax.swing.JButton();

        jbtn1 = new javax.swing.JButton();

        jbtn0 = new javax.swing.JButton();

        jbtnAdd = new javax.swing.JButton();

        jbtnMinus = new javax.swing.JButton();

        jbtnmultiply = new javax.swing.JButton();

        jbtnDivide = new javax.swing.JButton();

        jbtn5 = new javax.swing.JButton();

        jbtn6 = new javax.swing.JButton();

        jbtn2 = new javax.swing.JButton();

        jbtn3 = new javax.swing.JButton();

        jbtnDot = new javax.swing.JButton();

        jbtnEqual = new javax.swing.JButton();

        jbtnBackspace = new javax.swing.JButton();

        jButton20 = new javax.swing.JButton();

        jbtnc = new javax.swing.JButton();

        jBtn8 = new javax.swing.JButton();

        jbtn9 = new javax.swing.JButton();

        jbtnremindr = new javax.swing.JButton();

        jPanel5 = new javax.swing.JPanel();

        jBtnToatal = new javax.swing.JButton();

        jBtnReceipt = new javax.swing.JButton();

        jBtnRest = new javax.swing.JButton();

        jBtnExt = new javax.swing.JButton();

        jSAVE = new javax.swing.JButton();

        jBTNRECOR = new javax.swing.JButton();

        JBTNFILECHOS = new javax.swing.JButton();

        jPanel6 = new javax.swing.JPanel();

        jcobmCurence = new javax.swing.JComboBox<>();

        jTxtConvert = new javax.swing.JTextField();

        jBtnConvert = new javax.swing.JButton();

        jBtnClose = new javax.swing.JButton();

        jTxtconverted = new javax.swing.JTextField();

        jTextField1 = new javax.swing.JTextField();



        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);

        jPanel9.setLayout(jPanel9Layout);

        jPanel9Layout.setHorizontalGroup(

            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addGap(0, 100, Short.MAX_VALUE)

        );

        jPanel9Layout.setVerticalGroup(

            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addGap(0, 100, Short.MAX_VALUE)

        );



        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        setTitle("MUTESASIRA MOSES");

        setBackground(new java.awt.Color(0, 255, 255));

        setFont(new java.awt.Font("AcadEref", 1, 12)); // NOI18N



        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));



        jTxtMealCost.setEditable(false);

        jTxtMealCost.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTxtMealCost.setForeground(new java.awt.Color(255, 0, 0));

        jTxtMealCost.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTxtMealCost.setText("0");

        jTxtMealCost.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jTxtMealCostActionPerformed(evt);

            }

        });



        jtxtDrinkCost.setEditable(false);

        jtxtDrinkCost.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jtxtDrinkCost.setForeground(new java.awt.Color(255, 0, 0));



        jTxtDeliveryCost.setEditable(false);

        jTxtDeliveryCost.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTxtDeliveryCost.setForeground(new java.awt.Color(255, 0, 0));

        jTxtDeliveryCost.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jTxtDeliveryCostActionPerformed(evt);

            }

        });



        jTextField10.setEditable(false);

        jTextField10.setBackground(new java.awt.Color(255, 204, 204));

        jTextField10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextField10.setText("COST OF DRINKS");

        jTextField10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));



        jTextField11.setEditable(false);

        jTextField11.setBackground(new java.awt.Color(255, 204, 204));

        jTextField11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextField11.setText("COST OF MEAL ");

        jTextField11.setBorder(javax.swing.BorderFactory.createTitledBorder(""));



        jTextField12.setEditable(false);

        jTextField12.setBackground(new java.awt.Color(255, 204, 204));

        jTextField12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextField12.setText("COST OF DELIVERLY");

        jTextField12.setBorder(javax.swing.BorderFactory.createTitledBorder(""));



        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);

        jPanel1.setLayout(jPanel1Layout);

        jPanel1Layout.setHorizontalGroup(

            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addGroup(jPanel1Layout.createSequentialGroup()

                .addContainerGap()

                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)

                    .addGroup(jPanel1Layout.createSequentialGroup()

                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)

                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

                        .addComponent(jtxtDrinkCost, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))

                    .addGroup(jPanel1Layout.createSequentialGroup()

                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)

                            .addComponent(jTextField11)

                            .addComponent(jTextField12))

                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)

                            .addComponent(jTxtMealCost, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)

                            .addComponent(jTxtDeliveryCost))))

                .addContainerGap())

        );

        jPanel1Layout.setVerticalGroup(

            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addGroup(jPanel1Layout.createSequentialGroup()

                .addContainerGap()

                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)

                    .addComponent(jtxtDrinkCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)

                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))

                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)

                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)

                    .addComponent(jTxtMealCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)

                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))

                .addGap(27, 27, 27)

                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)

                    .addComponent(jTxtDeliveryCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)

                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))

                .addGap(46, 46, 46))

        );



        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));



        jChecbxChikBuger.setFont(new java.awt.Font("ISOCPEUR", 1, 11)); // NOI18N

        jChecbxChikBuger.setForeground(new java.awt.Color(0, 0, 204));

        jChecbxChikBuger.setText("CHICKEN BUGER");

        jChecbxChikBuger.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jChecbxChikBugerActionPerformed(evt);

            }

        });



        jChkbxBugerMeal.setFont(new java.awt.Font("ISOCPEUR", 1, 11)); // NOI18N

        jChkbxBugerMeal.setForeground(new java.awt.Color(0, 0, 204));

        jChkbxBugerMeal.setText("CHICKEN BUGER MEAL");

        jChkbxBugerMeal.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {

                jChkbxBugerMealMouseClicked(evt);

            }

        });

        jChkbxBugerMeal.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jChkbxBugerMealActionPerformed(evt);

            }

        });



        jCheckBxBacon.setFont(new java.awt.Font("ISOCPEUR", 1, 11)); // NOI18N

        jCheckBxBacon.setForeground(new java.awt.Color(0, 0, 204));

        jCheckBxBacon.setText("BACON AND CHEES BUGER");

        jCheckBxBacon.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jCheckBxBaconActionPerformed(evt);

            }

        });



        jTxtBugerNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTxtBugerNo.setForeground(new java.awt.Color(255, 0, 51));

        jTxtBugerNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jTxtBugerNo.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jTxtBugerNoActionPerformed(evt);

            }

        });



        jTxtBugerMeal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTxtBugerMeal.setForeground(new java.awt.Color(255, 0, 51));

        jTxtBugerMeal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jTxtBugerMeal.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jTxtBugerMealActionPerformed(evt);

            }

        });



        jTxtBacon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTxtBacon.setForeground(new java.awt.Color(255, 0, 51));

        jTxtBacon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));



        jTextField5.setEditable(false);

        jTextField5.setBackground(new java.awt.Color(255, 255, 0));

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jTextField5.setForeground(new java.awt.Color(0, 0, 204));

        jTextField5.setText("DRINKS");

        jTextField5.setBorder(null);



        jCombDrink.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jCombDrink.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT A DRINK", "APPLE JUICE", "TEA", "COLA", "COFEE", "ICE TEA", "ORANGE" }));

        jCombDrink.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jCombDrinkActionPerformed(evt);

            }

        });



        jCheckbxTax.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jCheckbxTax.setText("TAX");

        jCheckbxTax.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jCheckbxTaxActionPerformed(evt);

            }

        });



        jCheckBoxHomeDeliver.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jCheckBoxHomeDeliver.setText("HOME DELIVERY");

        jCheckBoxHomeDeliver.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jCheckBoxHomeDeliverActionPerformed(evt);

            }

        });



        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);

        jPanel2.setLayout(jPanel2Layout);

        jPanel2Layout.setHorizontalGroup(

            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addGroup(jPanel2Layout.createSequentialGroup()

                .addContainerGap()

                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

                    .addGroup(jPanel2Layout.createSequentialGroup()

                        .addComponent(jCheckbxTax)

                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

                        .addComponent(jCheckBoxHomeDeliver)

                        .addGap(36, 36, 36))

                    .addComponent(jSeparator1)

                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()

                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)

                            .addGroup(jPanel2Layout.createSequentialGroup()

                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)

                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

                                .addComponent(jCombDrink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)

                                .addGap(16, 16, 16))

                            .addGroup(jPanel2Layout.createSequentialGroup()

                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

                                    .addComponent(jChecbxChikBuger)

                                    .addComponent(jChkbxBugerMeal)

                                    .addComponent(jCheckBxBacon))

                                .addGap(46, 46, 46)

                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

                                    .addComponent(jTxtBacon, javax.swing.GroupLayout.Alignment.TRAILING)

                                    .addComponent(jTxtBugerMeal)

                                    .addComponent(jTxtBugerNo))))

                        .addContainerGap())))

        );

        jPanel2Layout.setVerticalGroup(

            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addGroup(jPanel2Layout.createSequentialGroup()

                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

                    .addGroup(jPanel2Layout.createSequentialGroup()

                        .addGap(15, 15, 15)

                        .addComponent(jChecbxChikBuger)

                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)

                        .addComponent(jChkbxBugerMeal))

                    .addGroup(jPanel2Layout.createSequentialGroup()

                        .addContainerGap()

                        .addComponent(jTxtBugerNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)

                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

                        .addComponent(jTxtBugerMeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))

                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

                    .addComponent(jCheckBxBacon)

                    .addComponent(jTxtBacon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))

                .addGap(18, 18, 18)

                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)

                    .addComponent(jCombDrink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))

                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)

                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)

                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)

                    .addComponent(jCheckbxTax)

                    .addComponent(jCheckBoxHomeDeliver))

                .addContainerGap())

        );



        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));



        jTextField13.setEditable(false);

        jTextField13.setBackground(new java.awt.Color(255, 204, 204));

        jTextField13.setColumns(4);

        jTextField13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextField13.setText("SUB TOTAL :");



        jTextField14.setEditable(false);

        jTextField14.setBackground(new java.awt.Color(255, 204, 204));

        jTextField14.setColumns(4);

        jTextField14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextField14.setText("TAX :");



        jTextField15.setEditable(false);

        jTextField15.setBackground(new java.awt.Color(255, 204, 204));

        jTextField15.setColumns(4);

        jTextField15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextField15.setText("TOTAL :");



        jTextSubtotal.setEditable(false);

        jTextSubtotal.setColumns(4);

        jTextSubtotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N



        jTextToatal.setEditable(false);

        jTextToatal.setColumns(4);

        jTextToatal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N



        jTextTax.setEditable(false);

        jTextTax.setColumns(4);

        jTextTax.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N



        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);

        jPanel3.setLayout(jPanel3Layout);

        jPanel3Layout.setHorizontalGroup(

            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addGroup(jPanel3Layout.createSequentialGroup()

                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)

                    .addGroup(jPanel3Layout.createSequentialGroup()

                        .addContainerGap(18, Short.MAX_VALUE)

                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)

                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)

                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))

                        .addGap(63, 63, 63)

                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

                            .addComponent(jTextTax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)

                            .addComponent(jTextSubtotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))

                    .addGroup(jPanel3Layout.createSequentialGroup()

                        .addGap(18, 18, 18)

                        .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)

                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

                        .addComponent(jTextToatal, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))

                .addContainerGap())

        );

        jPanel3Layout.setVerticalGroup(

            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addGroup(jPanel3Layout.createSequentialGroup()

                .addContainerGap()

                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

                    .addComponent(jTextSubtotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)

                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))

                .addGap(30, 30, 30)

                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)

                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)

                    .addComponent(jTextTax, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))

                .addGap(10, 10, 10)

                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

                    .addGroup(jPanel3Layout.createSequentialGroup()

                        .addGap(17, 17, 17)

                        .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))

                    .addComponent(jTextToatal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))

                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))

        );



        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));



        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));



        jPanel7.setBackground(new java.awt.Color(255, 255, 255));



        jTextArea1.setBackground(new java.awt.Color(255, 255, 204));

        jTextArea1.setColumns(20);

        jTextArea1.setFont(new java.awt.Font("FrankRuehl", 0, 16)); // NOI18N

        jTextArea1.setForeground(new java.awt.Color(0, 0, 255));

        jTextArea1.setRows(5);

        jScrollPane1.setViewportView(jTextArea1);



        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);

        jPanel7.setLayout(jPanel7Layout);

        jPanel7Layout.setHorizontalGroup(

            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)

        );

        jPanel7Layout.setVerticalGroup(

            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)

        );



        jTabbedPane1.addTab("RECEIPT", jPanel7);



        jPanel8.setBackground(new java.awt.Color(255, 255, 255));



        jTxtDisplay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTxtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);



        jBtn7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jBtn7.setText("7");

        jBtn7.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jBtn7ActionPerformed(evt);

            }

        });



        jbtn4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jbtn4.setText("4");

        jbtn4.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jbtn4ActionPerformed(evt);

            }

        });



        jbtn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jbtn1.setText("1");

        jbtn1.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jbtn1ActionPerformed(evt);

            }

        });



        jbtn0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jbtn0.setText("0");

        jbtn0.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jbtn0ActionPerformed(evt);

            }

        });



        jbtnAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jbtnAdd.setText("+");

        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jbtnAddActionPerformed(evt);

            }

        });



        jbtnMinus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jbtnMinus.setText("-");

        jbtnMinus.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jbtnMinusActionPerformed(evt);

            }

        });



        jbtnmultiply.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jbtnmultiply.setText("*");

        jbtnmultiply.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jbtnmultiplyActionPerformed(evt);

            }

        });



        jbtnDivide.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jbtnDivide.setText("/");

        jbtnDivide.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jbtnDivideActionPerformed(evt);

            }

        });



        jbtn5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jbtn5.setText("5");

        jbtn5.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jbtn5ActionPerformed(evt);

            }

        });



        jbtn6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jbtn6.setText("6");

        jbtn6.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jbtn6ActionPerformed(evt);

            }

        });



        jbtn2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jbtn2.setText("2");

        jbtn2.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jbtn2ActionPerformed(evt);

            }

        });



        jbtn3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jbtn3.setText("3");

        jbtn3.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jbtn3ActionPerformed(evt);

            }

        });



        jbtnDot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jbtnDot.setText(".");

        jbtnDot.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jbtnDotActionPerformed(evt);

            }

        });



        jbtnEqual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jbtnEqual.setText("=");

        jbtnEqual.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jbtnEqualActionPerformed(evt);

            }

        });



        jbtnBackspace.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N

        jbtnBackspace.setText("←");

        jbtnBackspace.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jbtnBackspaceActionPerformed(evt);

            }

        });



        jButton20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jButton20.setText("+/-");

        jButton20.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jButton20ActionPerformed(evt);

            }

        });



        jbtnc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jbtnc.setText("c");

        jbtnc.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jbtncActionPerformed(evt);

            }

        });



        jBtn8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jBtn8.setText("8");

        jBtn8.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jBtn8ActionPerformed(evt);

            }

        });



        jbtn9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jbtn9.setText("9");

        jbtn9.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jbtn9ActionPerformed(evt);

            }

        });



        jbtnremindr.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jbtnremindr.setText("%");

        jbtnremindr.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jbtnremindrActionPerformed(evt);

            }

        });



        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);

        jPanel8.setLayout(jPanel8Layout);

        jPanel8Layout.setHorizontalGroup(

            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addGroup(jPanel8Layout.createSequentialGroup()

                .addGap(39, 39, 39)

                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)

                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

                        .addGroup(jPanel8Layout.createSequentialGroup()

                            .addComponent(jBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)

                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)

                            .addComponent(jBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)

                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

                            .addComponent(jbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)

                            .addGap(2, 2, 2)

                            .addComponent(jbtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))

                        .addGroup(jPanel8Layout.createSequentialGroup()

                            .addComponent(jbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)

                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

                            .addComponent(jbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)

                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

                            .addComponent(jbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)

                            .addGap(10, 10, 10)

                            .addComponent(jbtnmultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))

                        .addGroup(jPanel8Layout.createSequentialGroup()

                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

                                .addGroup(jPanel8Layout.createSequentialGroup()

                                    .addComponent(jbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)

                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

                                    .addComponent(jbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)

                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)

                                    .addComponent(jbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))

                                .addGroup(jPanel8Layout.createSequentialGroup()

                                    .addComponent(jbtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)

                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

                                    .addComponent(jbtnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)

                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

                                    .addComponent(jbtnremindr, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))

                            .addGap(2, 2, 2)

                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)

                                .addComponent(jbtnEqual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

                                .addComponent(jbtnDivide, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))))

                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

                        .addComponent(jTxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)

                        .addGroup(jPanel8Layout.createSequentialGroup()

                            .addComponent(jbtnBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)

                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)

                            .addComponent(jbtnc, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)

                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

                            .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)

                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

                            .addComponent(jbtnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))

                .addContainerGap(172, Short.MAX_VALUE))

        );

        jPanel8Layout.setVerticalGroup(

            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addGroup(jPanel8Layout.createSequentialGroup()

                .addContainerGap()

                .addComponent(jTxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)

                .addGap(18, 18, 18)

                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)

                    .addComponent(jbtnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)

                    .addComponent(jbtnc, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)

                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)

                    .addComponent(jbtnBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))

                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

                    .addGroup(jPanel8Layout.createSequentialGroup()

                        .addGap(77, 77, 77)

                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)

                            .addComponent(jbtnmultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)

                            .addComponent(jbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)

                            .addComponent(jbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)

                            .addComponent(jbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))

                    .addGroup(jPanel8Layout.createSequentialGroup()

                        .addGap(18, 18, 18)

                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

                            .addComponent(jBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)

                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)

                                .addComponent(jbtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)

                                .addComponent(jBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)

                                .addComponent(jbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))))

                .addGap(18, 18, 18)

                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)

                    .addComponent(jbtnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)

                    .addComponent(jbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)

                    .addComponent(jbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)

                    .addComponent(jbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))

                .addGap(18, 18, 18)

                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)

                    .addComponent(jbtnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)

                    .addComponent(jbtnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)

                    .addComponent(jbtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)

                    .addComponent(jbtnremindr, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))

                .addContainerGap(91, Short.MAX_VALUE))

        );



        jTabbedPane1.addTab("CALCULATOR", jPanel8);



        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);

        jPanel4.setLayout(jPanel4Layout);

        jPanel4Layout.setHorizontalGroup(

            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addGroup(jPanel4Layout.createSequentialGroup()

                .addContainerGap()

                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)

                .addContainerGap(20, Short.MAX_VALUE))

        );

        jPanel4Layout.setVerticalGroup(

            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addGroup(jPanel4Layout.createSequentialGroup()

                .addContainerGap()

                .addComponent(jTabbedPane1)

                .addContainerGap())

        );



        jPanel5.setBackground(new java.awt.Color(255, 204, 204));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));



        jBtnToatal.setBackground(new java.awt.Color(0, 255, 255));

        jBtnToatal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jBtnToatal.setForeground(new java.awt.Color(204, 0, 255));

        jBtnToatal.setText("TOTAL");

        jBtnToatal.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jBtnToatalActionPerformed(evt);

            }

        });



        jBtnReceipt.setBackground(new java.awt.Color(0, 255, 255));

        jBtnReceipt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jBtnReceipt.setForeground(new java.awt.Color(204, 0, 255));

        jBtnReceipt.setText("RECEIPT");

        jBtnReceipt.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jBtnReceiptActionPerformed(evt);

            }

        });



        jBtnRest.setBackground(new java.awt.Color(0, 255, 255));

        jBtnRest.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jBtnRest.setForeground(new java.awt.Color(204, 0, 255));

        jBtnRest.setText("RESET");

        jBtnRest.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jBtnRestActionPerformed(evt);

            }

        });



        jBtnExt.setBackground(new java.awt.Color(0, 255, 255));

        jBtnExt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jBtnExt.setForeground(new java.awt.Color(204, 0, 255));

        jBtnExt.setText("EXIT");

        jBtnExt.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jBtnExtActionPerformed(evt);

            }

        });



        jSAVE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jSAVE.setForeground(new java.awt.Color(255, 0, 51));

        jSAVE.setText("SAVE");

        jSAVE.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jSAVEActionPerformed(evt);

            }

        });



        jBTNRECOR.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jBTNRECOR.setForeground(new java.awt.Color(0, 0, 255));

        jBTNRECOR.setText("RECORDS");

        jBTNRECOR.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {

                jBTNRECORMouseClicked(evt);

            }

        });

        jBTNRECOR.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jBTNRECORActionPerformed(evt);

            }

        });



        JBTNFILECHOS.setText("FILE CHHOSE");

        JBTNFILECHOS.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                JBTNFILECHOSActionPerformed(evt);

            }

        });



        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);

        jPanel5.setLayout(jPanel5Layout);

        jPanel5Layout.setHorizontalGroup(

            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addGroup(jPanel5Layout.createSequentialGroup()

                .addGap(103, 103, 103)

                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

                    .addComponent(jBtnToatal)

                    .addComponent(JBTNFILECHOS))

                .addGap(102, 102, 102)

                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

                    .addGroup(jPanel5Layout.createSequentialGroup()

                        .addComponent(jSAVE, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)

                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

                        .addComponent(jBTNRECOR))

                    .addGroup(jPanel5Layout.createSequentialGroup()

                        .addComponent(jBtnReceipt)

                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

                        .addComponent(jBtnRest)))

                .addGap(73, 73, 73)

                .addComponent(jBtnExt)

                .addGap(34, 34, 34))

        );

        jPanel5Layout.setVerticalGroup(

            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addGroup(jPanel5Layout.createSequentialGroup()

                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)

                    .addComponent(jBtnExt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)

                    .addComponent(jBtnRest, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)

                    .addComponent(jBtnReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)

                    .addComponent(jBtnToatal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))

                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)

                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)

                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)

                        .addComponent(jSAVE, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)

                        .addComponent(JBTNFILECHOS))

                    .addComponent(jBTNRECOR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))

                .addGap(6, 6, 6))

        );



        jPanel6.setBackground(new java.awt.Color(255, 204, 204));

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));



        jcobmCurence.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        jcobmCurence.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHOOSE ONE..", "USA", "NIGERIA", "KENYAN", "CANADA", "BRAZIL", "INDONESIA", "PHILIPINE" }));

        jcobmCurence.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jcobmCurenceActionPerformed(evt);

            }

        });



        jTxtConvert.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTxtConvert.setForeground(new java.awt.Color(102, 255, 0));

        jTxtConvert.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTxtConvert.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jTxtConvertActionPerformed(evt);

            }

        });



        jBtnConvert.setBackground(new java.awt.Color(255, 204, 204));

        jBtnConvert.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jBtnConvert.setForeground(new java.awt.Color(0, 0, 255));

        jBtnConvert.setText("CONVERT");

        jBtnConvert.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jBtnConvertActionPerformed(evt);

            }

        });



        jBtnClose.setBackground(new java.awt.Color(255, 204, 255));

        jBtnClose.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jBtnClose.setForeground(new java.awt.Color(0, 0, 204));

        jBtnClose.setText("CLOSE");

        jBtnClose.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jBtnCloseActionPerformed(evt);

            }

        });



        jTxtconverted.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N



        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);

        jPanel6.setLayout(jPanel6Layout);

        jPanel6Layout.setHorizontalGroup(

            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addGroup(jPanel6Layout.createSequentialGroup()

                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()

                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)

                            .addComponent(jTxtconverted, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)

                            .addComponent(jTxtConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))

                        .addGap(76, 76, 76))

                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()

                        .addComponent(jBtnConvert)

                        .addGap(62, 62, 62)

                        .addComponent(jBtnClose)

                        .addGap(66, 66, 66))

                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()

                        .addComponent(jcobmCurence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)

                        .addGap(92, 92, 92))))

        );

        jPanel6Layout.setVerticalGroup(

            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addGroup(jPanel6Layout.createSequentialGroup()

                .addContainerGap()

                .addComponent(jcobmCurence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)

                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

                    .addGroup(jPanel6Layout.createSequentialGroup()

                        .addGap(18, 18, 18)

                        .addComponent(jTxtConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)

                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)

                        .addComponent(jTxtconverted, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)

                        .addGap(0, 0, Short.MAX_VALUE))

                    .addGroup(jPanel6Layout.createSequentialGroup()

                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)

                            .addComponent(jBtnConvert)

                            .addComponent(jBtnClose))

                        .addContainerGap())))

        );



        jTextField1.setEditable(false);

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));

        jTextField1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N

        jTextField1.setForeground(new java.awt.Color(51, 0, 153));

        jTextField1.setText("RESTAURANT MANAGEMENT SYSTEM");

        jTextField1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jTextField1ActionPerformed(evt);

            }

        });



        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());

        getContentPane().setLayout(layout);

        layout.setHorizontalGroup(

            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addGroup(layout.createSequentialGroup()

                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

                    .addGroup(layout.createSequentialGroup()

                        .addGap(42, 42, 42)

                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)

                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

                            .addGroup(layout.createSequentialGroup()

                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))

                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)

                                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))

                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))

                    .addGroup(layout.createSequentialGroup()

                        .addGap(161, 161, 161)

                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))

                .addGap(588, 588, 588))

        );

        layout.setVerticalGroup(

            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addGroup(layout.createSequentialGroup()

                .addGap(35, 35, 35)

                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)

                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)

                    .addGroup(layout.createSequentialGroup()

                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)

                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))

                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)

                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))

                        .addGap(9, 9, 9)

                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))

                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))

                .addGap(550, 550, 550))

        );



        pack();

    }// </editor-fold>//GEN-END:initComponents

 

          

           

    

    private void jChkbxBugerMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkbxBugerMealActionPerformed

        

    }//GEN-LAST:event_jChkbxBugerMealActionPerformed



    private void jTxtBugerNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtBugerNoActionPerformed

        // TODO add your handling code here:

    }//GEN-LAST:event_jTxtBugerNoActionPerformed



    private void jCheckBoxHomeDeliverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxHomeDeliverActionPerformed

      double delivery = 3.39;

      if(jCheckBoxHomeDeliver.isSelected() ){

      String deliv = String.format("%.2f", delivery);

      jTxtDeliveryCost.setText( deliv);

      }

      else{

      jTxtDeliveryCost.setText(null);

      } 

    }//GEN-LAST:event_jCheckBoxHomeDeliverActionPerformed



    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed

        String EnterNumber = jTxtDisplay.getText () + jbtn3.getText();

       jTxtDisplay.setText (EnterNumber); 

    }//GEN-LAST:event_jbtn3ActionPerformed



    private void jbtnmultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmultiplyActionPerformed

      firstnum = Double.parseDouble(jTxtDisplay.getText ());//make the existing text double

       jTxtDisplay.setText ("");// empty rhe jtext display

       Operations = "*";// assig the operation

    }//GEN-LAST:event_jbtnmultiplyActionPerformed



    private void jbtncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncActionPerformed

  

       jTxtDisplay.setText ("");       

    }//GEN-LAST:event_jbtncActionPerformed



    private void jbtnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDivideActionPerformed

       firstnum = Double.parseDouble(jTxtDisplay.getText ());//make the existing text double

       jTxtDisplay.setText ("");// empty rhe jtext display

       Operations = "/";// assig the operation

    }//GEN-LAST:event_jbtnDivideActionPerformed



    private void jbtnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEqualActionPerformed

         Double  result;

        String answer;

         secondnum = Double.parseDouble(jTxtDisplay.getText());

         if (Operations == "+"){

         result = firstnum + secondnum ;

         answer = String.format("%.2f", result);

           jTxtDisplay.setText (answer);

         }   

         else if (Operations == "-"){

            result = firstnum + secondnum ;

         answer = String.format("%.2f", result);

           jTxtDisplay.setText (answer);

         }  

         else if (Operations == "*"){

            result = firstnum * secondnum ;

         answer = String.format("%.2f", result);

           jTxtDisplay.setText (answer);

         }

         else if (Operations == "/"){

            result = firstnum / secondnum ;

         answer = String.format("%.2f", result);

           jTxtDisplay.setText (firstnum + "/" + secondnum +"=" + answer);

         }

         else if (Operations == "%"){

            result = firstnum % secondnum ;

         answer = String.format("%.2f", result);

           jTxtDisplay.setText (answer);

         }

      

    }//GEN-LAST:event_jbtnEqualActionPerformed

    

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed

          Double db = Double.parseDouble(String.valueOf(jTxtDisplay.getText()));

          db = db * (-1);   

            jTxtDisplay.setText(String.valueOf(db));

    }//GEN-LAST:event_jButton20ActionPerformed



    private void jbtnBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackspaceActionPerformed

        String backspace = null;

      

        if (jTxtDisplay.getText().length() > 0){

            StringBuilder strb = new  StringBuilder(jTxtDisplay.getText());

            strb.deleteCharAt(jTxtDisplay.getText() .length()-1);

            backspace = strb.toString();

            jTxtDisplay.setText(backspace);

        }

    }//GEN-LAST:event_jbtnBackspaceActionPerformed



    private void jBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn7ActionPerformed

       String EnterNumber = jTxtDisplay.getText () + jBtn7.getText();

       jTxtDisplay.setText (EnterNumber);

    }//GEN-LAST:event_jBtn7ActionPerformed



    private void jBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn8ActionPerformed

        String EnterNumber = jTxtDisplay.getText () + jBtn8.getText();

       jTxtDisplay.setText (EnterNumber);

    }//GEN-LAST:event_jBtn8ActionPerformed



    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed

       String EnterNumber = jTxtDisplay.getText () + jbtn9.getText();

       jTxtDisplay.setText (EnterNumber);

    }//GEN-LAST:event_jbtn9ActionPerformed



    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed

      firstnum = Double.parseDouble(jTxtDisplay.getText ());//make the existing text double

       jTxtDisplay.setText ("");// empty rhe jtext display

       Operations = "+";// assig the operation;

    }//GEN-LAST:event_jbtnAddActionPerformed



    private void jbtnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMinusActionPerformed

        firstnum = Double.parseDouble(jTxtDisplay.getText ());//make the existing text double

       jTxtDisplay.setText ("");// empty rhe jtext display

       Operations = "-";// assig the operation

    }//GEN-LAST:event_jbtnMinusActionPerformed



    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed

      String EnterNumber =  jTxtDisplay.getText () + jbtn4.getText();

       jTxtDisplay.setText (EnterNumber);

    }//GEN-LAST:event_jbtn4ActionPerformed



    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed

        String EnterNumber =  jTxtDisplay.getText () + jbtn5.getText();

       jTxtDisplay.setText (EnterNumber);

    }//GEN-LAST:event_jbtn5ActionPerformed



    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed

      String EnterNumber =  jTxtDisplay.getText () +jbtn6.getText();

       jTxtDisplay.setText (EnterNumber);

    }//GEN-LAST:event_jbtn6ActionPerformed



    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed

       String EnterNumber =  jTxtDisplay.getText () +jbtn1.getText();

       jTxtDisplay.setText (EnterNumber);

    }//GEN-LAST:event_jbtn1ActionPerformed



    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed

        String EnterNumber =  jTxtDisplay.getText () +jbtn2.getText();

       jTxtDisplay.setText (EnterNumber);

    }//GEN-LAST:event_jbtn2ActionPerformed



    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed

         String EnterNumber =  jTxtDisplay.getText () +jbtn0.getText();

       jTxtDisplay.setText (EnterNumber);

    }//GEN-LAST:event_jbtn0ActionPerformed



    private void jbtnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDotActionPerformed

      String EnterNumber =  jTxtDisplay.getText () + jbtnDot.getText();

       jTxtDisplay.setText (EnterNumber);

    }//GEN-LAST:event_jbtnDotActionPerformed



    private void jbtnremindrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnremindrActionPerformed

         firstnum = Double.parseDouble(jTxtDisplay.getText ());//make the existing text double

       jTxtDisplay.setText ("");// empty rhe jtext display

       Operations = "%";// assins the operation

    }//GEN-LAST:event_jbtnremindrActionPerformed



    private void jcobmCurenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcobmCurenceActionPerformed

        // TODO add your handling code here:

    }//GEN-LAST:event_jcobmCurenceActionPerformed



    private void jBtnToatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnToatalActionPerformed

        double d1 = Double.parseDouble(jtxtDrinkCost.getText());

         double d2 = Double.parseDouble(jTxtMealCost.getText());

         double d3 = Double.parseDouble(jTxtDeliveryCost.getText());

          double d4 = Double.parseDouble(jTextTax.getText());

          double subtatl = d1 + d2 + d3;

          double total = subtatl + d4;

          String subtt = String.format("%.2f",subtatl );

          String tt = String.format("%.2f",total );

          jTextSubtotal.setText("£"+ subtt);

          jTextToatal.setText("£"+ tt);

         

    }//GEN-LAST:event_jBtnToatalActionPerformed



    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField1ActionPerformed



    private void jBtnReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnReceiptActionPerformed

      

        String a = "THE RECEPT \n";

        String b= "thx dia , come gain\n";

        String c = "Drinks : " + jtxtDrinkCost.getText()+ "\n"; 

        String d = "Meals : " + jTxtMealCost.getText() + "\n";

        String e = "Delivery cost: " + jTxtDeliveryCost.getText() + "\n";

        String f = "tax : " + jTextTax.getText() + "\n";

        String g = "toal : " + jTextToatal.getText() + "\n";

        

        

        

        jTextArea1.setText ( a + c+d + e + f + g + b);

    }//GEN-LAST:event_jBtnReceiptActionPerformed



    private void jBtnRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRestActionPerformed

       jTxtDeliveryCost.setText(null);

       jtxtDrinkCost.setText(null);

       jTxtMealCost.setText("0");

       jTextSubtotal.setText(null);

       jTextTax.setText(null);

       jTextToatal.setText(null);

    }//GEN-LAST:event_jBtnRestActionPerformed



    private void jBtnExtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExtActionPerformed

     System.exit(0); //it exists the program

    }//GEN-LAST:event_jBtnExtActionPerformed



    private void jBtnConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConvertActionPerformed

       int NigeriaNira= 3;

       int USAdl = 2;

        int KENYANshs = 1000;

         int CANADAdl = 15;

          int BRAZILpd = 50;

           int INDONESIAcn = 188;

           int PHILIPINEdd = 233;

        Double BritishPound =Double .parseDouble(jTxtConvert.getText());// GET the string in the convert textfiel and makes it double

        if(jcobmCurence.getSelectedItem().equals("NIGERIA")){

        String Convert1 = String.format("N %.2f",BritishPound * NigeriaNira );

        jTxtconverted.setText(Convert1);// DISPALYS THE CONVERTED VALUE ON SCREEN

        }

        else if (jcobmCurence.getSelectedItem().equals("USA")){

        String Convert2 = String.format("USD %.2f",BritishPound * USAdl );

        jTxtconverted.setText(Convert2);

        }

        else if (jcobmCurence.getSelectedItem().equals("KENYAN")){

        String Convert3 = String.format("KS %.2f",BritishPound * KENYANshs  );

        jTxtconverted.setText(Convert3);

        }

        else if (jcobmCurence.getSelectedItem().equals("CANADA")){

        String Convert4 = String.format("CN %.2f",BritishPound * CANADAdl  );

        jTxtconverted.setText(Convert4);

        }

        else if (jcobmCurence.getSelectedItem().equals("BRAZIL")){

        String Convert5 = String.format("BZ %.2f",BritishPound * BRAZILpd  );

        jTxtconverted.setText(Convert5);

        }

         else if (jcobmCurence.getSelectedItem().equals("INDONESIA")){

        String Convert6 = String.format("ID %.2f",BritishPound * INDONESIAcn  );

        jTxtconverted.setText(Convert6);

         }

        else if (jcobmCurence.getSelectedItem().equals("PHILIPINE")){

        String Convert6 = String.format("PP %.2f",BritishPound * PHILIPINEdd  );

        jTxtconverted.setText(Convert6);

         }

    }//GEN-LAST:event_jBtnConvertActionPerformed



    private void jTxtConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtConvertActionPerformed

        // TODO add your handling code here:

    }//GEN-LAST:event_jTxtConvertActionPerformed



    private void jCombDrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombDrinkActionPerformed

         double APP = 1.5;

         double TEALEJUICE = 5;

        double COLA = 6;

       double COFEE = 6.7;

        double ICETEA = 9.5;

         double ORANGE = 9.3;

   

        if(jCombDrink.getSelectedItem().equals("APPLE JUICE")){

        String Convert1 = String.format("%.2f", APP  );

        jtxtDrinkCost.setText(Convert1);}// DISPALYS THE CONVERTED VALUE ON SCREEN

        

        else if(jCombDrink.getSelectedItem().equals("TEA")){

        String Convert2 = String.format(" %.2f", TEALEJUICE  );

        jtxtDrinkCost.setText( Convert2);}// DISPALYS THE CONVERTED VALUE ON SCREEN

        

        else if(jCombDrink.getSelectedItem().equals("COLA")){

        String Convert3 = String.format(" %.2f", COLA  );

        jtxtDrinkCost.setText(Convert3);}// DISPALYS THE CONVERTED VALUE ON SCREEN

      

        else if(jCombDrink.getSelectedItem().equals("COFEE")){

        String Convert4 = String.format(" %.2f", COFEE  );

        jtxtDrinkCost.setText(Convert4);}// DISPALYS THE CONVERTED VALUE ON SCREEN

        

         else if(jCombDrink.getSelectedItem().equals("ICE TEA")){

        String Convert5 = String.format(" %.2f", ICETEA  );

        jtxtDrinkCost.setText(Convert5);}// DISPALYS THE CONVERTED VALUE ON SCREEN

        

          else if(jCombDrink.getSelectedItem().equals("ORANGE")){

        String Convert6 = String.format(" %.2f", ORANGE  );

        jtxtDrinkCost.setText(Convert6);}// DISPALYS THE CONVERTED VALUE ON SCREEN

        else if(jCombDrink.getSelectedItem().equals("SELECT A DRINK")){

     

        jtxtDrinkCost.setText("");}// 

        

         

    }//GEN-LAST:event_jCombDrinkActionPerformed



    private void jChecbxChikBugerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChecbxChikBugerActionPerformed

         double otherMealCost = Double.parseDouble(jTxtMealCost.getText()); 

        double bugerno = Double.parseDouble(jTxtBugerNo.getText()); 

        double bugerprice= 2.4;

        if(jChecbxChikBuger.isSelected()){

                double total = (bugerprice * bugerno) + otherMealCost ;

                String mealcost = String.format("%.2f",total );

                jTxtMealCost.setText(mealcost);

                        }

        

  

    }//GEN-LAST:event_jChecbxChikBugerActionPerformed



    private void jCheckBxBaconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBxBaconActionPerformed

          double otherMealCost = Double.parseDouble(jTxtMealCost.getText()); 

        double bugernoo = Double.parseDouble(jTxtBacon.getText()); 

        double bugerprice1= 2.7;

        if(jCheckBxBacon.isSelected()){

                double total = (bugerprice1 * bugernoo) + otherMealCost ;

                String mealcost1 = String.format("%.2f",total );

                jTxtMealCost.setText(mealcost1);

                        }

    }//GEN-LAST:event_jCheckBxBaconActionPerformed



    private void jTxtDeliveryCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtDeliveryCostActionPerformed

        // TODO add your handling code here:

    }//GEN-LAST:event_jTxtDeliveryCostActionPerformed



    private void jTxtMealCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtMealCostActionPerformed

        // TODO add your handling code here:

    }//GEN-LAST:event_jTxtMealCostActionPerformed



    private void jChkbxBugerMealMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkbxBugerMealMouseClicked

  double otherMealCost = Double.parseDouble(jTxtMealCost.getText()); 

        double bugernoo = Double.parseDouble(jTxtBugerMeal.getText()); 

        double bugerprice1= 2.7;

        if(jChkbxBugerMeal.isSelected()){

                double total = (bugerprice1 * bugernoo) + otherMealCost ;

                String mealcost1 = String.format("%.2f",total );

                jTxtMealCost.setText(mealcost1);

                        }       

    }//GEN-LAST:event_jChkbxBugerMealMouseClicked



    private void jTxtBugerMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtBugerMealActionPerformed

        // TODO add your handling code here:

    }//GEN-LAST:event_jTxtBugerMealActionPerformed



    private void jCheckbxTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckbxTaxActionPerformed

        double delivery = 1.39;

      if(jCheckbxTax.isSelected() ){

      String deliv = String.format("%.2f", delivery);

      jTextTax.setText(deliv);

      }

      else{

      jTextTax.setText(null);}

    }//GEN-LAST:event_jCheckbxTaxActionPerformed



    private void jBtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCloseActionPerformed

       jTxtconverted.setText("");

               jTxtConvert.setText("");

    }//GEN-LAST:event_jBtnCloseActionPerformed



    private void jSAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSAVEActionPerformed

             JOptionPane.showMessageDialog(null,"SAVE DATA?");

        

         try(FileWriter fw = new FileWriter("C:/Users/Dell/Desktop/FL/RESTAURANT.txt" , true);
    BufferedWriter bw = new BufferedWriter(fw);
    PrintWriter out = new PrintWriter(bw))
{
    out.println(jTextArea1.getText()); 
    //more code
   // out.println("waaa");
    //more code
} catch (IOException e) {
    //exception handling left as an exercise for the reader

    }{}

          

          

       
       

    }//GEN-LAST:event_jSAVEActionPerformed



    private void jBTNRECORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTNRECORActionPerformed

 try (
          BufferedReader in = new  BufferedReader(new FileReader("C:/Users/Dell/Desktop/FL/RESTAURANT.txt"));// u can actualy feed in  any directory
           // BufferedWriter out =  new  BufferedWriter ( new  FileWriter ("C:/Users/Dell/Desktop/FL/momom1.txt")); //creates a new file 
               )
       {
           int c;
           while((c= in.read()) != -1 ) {
               ///System.out.write(c);} IF U WANT IT TO PRINT ON THE SCREEN
           jTextArea1.read(in, null);
           }
          
           } catch(FileNotFoundException e){} 
            catch(IOException e1){} 
              

    }//GEN-LAST:event_jBTNRECORActionPerformed



    private void jBTNRECORMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBTNRECORMouseClicked

             





    }//GEN-LAST:event_jBTNRECORMouseClicked



    private void JBTNFILECHOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTNFILECHOSActionPerformed

//    CHOOSEF dd = new CHOOSEF ();

//    dd.ME();

//      

    }//GEN-LAST:event_JBTNFILECHOSActionPerformed



    /**

     * @param args the command line arguments

     */

    public static void main(String args[]) {

        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">

        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.

         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 

         */

        try {

            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {

                if ("Nimbus".equals(info.getName())) {

                    javax.swing.UIManager.setLookAndFeel(info.getClassName());

                    break;

                }

            }

        } catch (ClassNotFoundException ex) {

            java.util.logging.Logger.getLogger(rest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {

            java.util.logging.Logger.getLogger(rest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {

            java.util.logging.Logger.getLogger(rest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {

            java.util.logging.Logger.getLogger(rest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }

        //</editor-fold>



        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                new rest().setVisible(true);

            }

        });

       

    }



    // Variables declaration - do not modify//GEN-BEGIN:variables

    private javax.swing.JButton JBTNFILECHOS;

    private javax.swing.JButton jBTNRECOR;

    private javax.swing.JButton jBtn7;

    private javax.swing.JButton jBtn8;

    private javax.swing.JButton jBtnClose;

    private javax.swing.JButton jBtnConvert;

    private javax.swing.JButton jBtnExt;

    private javax.swing.JButton jBtnReceipt;

    private javax.swing.JButton jBtnRest;

    private javax.swing.JButton jBtnToatal;

    private javax.swing.JButton jButton20;

    private javax.swing.JCheckBox jChecbxChikBuger;

    private javax.swing.JCheckBox jCheckBoxHomeDeliver;

    private javax.swing.JCheckBox jCheckBxBacon;

    private javax.swing.JCheckBox jCheckbxTax;

    private javax.swing.JCheckBox jChkbxBugerMeal;

    private javax.swing.JComboBox<String> jCombDrink;

    private javax.swing.JPanel jPanel1;

    private javax.swing.JPanel jPanel2;

    private javax.swing.JPanel jPanel3;

    private javax.swing.JPanel jPanel4;

    private javax.swing.JPanel jPanel5;

    private javax.swing.JPanel jPanel6;

    private javax.swing.JPanel jPanel7;

    private javax.swing.JPanel jPanel8;

    private javax.swing.JPanel jPanel9;

    private javax.swing.JButton jSAVE;

    private javax.swing.JScrollPane jScrollPane1;

    private javax.swing.JSeparator jSeparator1;

    private javax.swing.JTabbedPane jTabbedPane1;

    private javax.swing.JTextArea jTextArea1;

    private javax.swing.JTextField jTextField1;

    private javax.swing.JTextField jTextField10;

    private javax.swing.JTextField jTextField11;

    private javax.swing.JTextField jTextField12;

    private javax.swing.JTextField jTextField13;

    private javax.swing.JTextField jTextField14;

    private javax.swing.JTextField jTextField15;

    private javax.swing.JTextField jTextField5;

    private javax.swing.JTextField jTextSubtotal;

    private javax.swing.JTextField jTextTax;

    private javax.swing.JTextField jTextToatal;

    private javax.swing.JTextField jTxtBacon;

    private javax.swing.JTextField jTxtBugerMeal;

    private javax.swing.JTextField jTxtBugerNo;

    private javax.swing.JTextField jTxtConvert;

    private javax.swing.JTextField jTxtDeliveryCost;

    private javax.swing.JTextField jTxtDisplay;

    private javax.swing.JTextField jTxtMealCost;

    private javax.swing.JTextField jTxtconverted;

    private javax.swing.JButton jbtn0;

    private javax.swing.JButton jbtn1;

    private javax.swing.JButton jbtn2;

    private javax.swing.JButton jbtn3;

    private javax.swing.JButton jbtn4;

    private javax.swing.JButton jbtn5;

    private javax.swing.JButton jbtn6;

    private javax.swing.JButton jbtn9;

    private javax.swing.JButton jbtnAdd;

    private javax.swing.JButton jbtnBackspace;

    private javax.swing.JButton jbtnDivide;

    private javax.swing.JButton jbtnDot;

    private javax.swing.JButton jbtnEqual;

    private javax.swing.JButton jbtnMinus;

    private javax.swing.JButton jbtnc;

    private javax.swing.JButton jbtnmultiply;

    private javax.swing.JButton jbtnremindr;

    private javax.swing.JComboBox<String> jcobmCurence;

    private javax.swing.JTextField jtxtDrinkCost;

    // End of variables declaration//GEN-END:variables

    private String x;

     int c;

}

